
/* definitions */

%{
#include <stdio.h>
#include <stdlib.h>
#include "tokendef.h"

 /* integers to track line and column numbers */
int scancol = 1;
int yycol = 1;
int scanlineno = 1;

 /* char pointer to pass error messages to driver.c */
char *yyerror = NULL;

 /* TODO: functions to update line and column numbers */
void updateCol();
void countLines();

 /* TODO: function to process a string literal */
int processString();

%}

newline         \n
whitespace      [ \t\r]+ 
integer         0|[1-9][0-9]*
integerlead0    0[0-9]+
character       \'[^\'\n]\'

 /* String can contain any characters between the double quotes */
 /* other than a newline or unescaped doublequotes */

string       a^


 /* If the end quote is not found in the same line the string is unterminated */
untermstring //TODO

comment         a^
multlncomment   a^
untermcomment   a^

identifier      [A-Za-z][A-Za-z0-9]*
illidentifier   [0-9]+[A-Za-z][A-Za-z0-9]*

yylineno = 1;

%%

 /* rules */

 /* Keywords */
 "if"        { updateCol(); return KWD_IF; }
 "else"      { updateCol(); return KWD_ELSE; }
 "while"     { updateCol(); return KWD_WHILE; }
 "int"       { updateCol(); return KWD_INT; }
 "string"    { updateCol(); return KWD_STRING; }
 "char"      { updateCol(); return KWD_CHAR; }
 "return"    { updateCol(); return KWD_RETURN; }
 "void"      { updateCol(); return KWD_VOID; }

 /* Operators */
  /* Two character operators */
 "++"        { updateCol(); return OPER_INC; }
 "--"        { updateCol(); return OPER_DEC; }
 "<="        { updateCol(); return OPER_LTE; }
 ">="        { updateCol(); return OPER_GTE; }
 "=="        { updateCol(); return OPER_EQ; }
 "!="        { updateCol(); return OPER_NEQ; }
 "&&"        { updateCol(); return OPER_AND; }
 "||"        { updateCol(); return OPER_OR; }

 /* One character operators */
 "+"         { updateCol(); return OPER_ADD; }
 "-"         { updateCol(); return OPER_SUB; }
 "*"         { updateCol(); return OPER_MUL; }
 "/"         { updateCol(); return OPER_DIV; }
 "%"         { updateCol(); return OPER_MOD; }
 "<"         { updateCol(); return OPER_LT; }
 ">"         { updateCol(); return OPER_GT; }
 "="         { updateCol(); return OPER_ASGN; }
 "!"         { updateCol(); return OPER_NOT; }
 "@"         { updateCol(); return OPER_AT; }
 /* Brackets and punctuation */
 "["         { updateCol(); return LSQ_BRKT; }
 "]"         { updateCol(); return RSQ_BRKT; }
 "{"         { updateCol(); return LCRLY_BRKT; }
 "}"         { updateCol(); return RCRLY_BRKT; }
 "("         { updateCol(); return LPAREN; }
 ")"         { updateCol(); return RPAREN; }
 ","         { updateCol(); return COMMA; }
 ";"         { updateCol(); return SEMICLN; }

 /* Identifiers */
{identifier} {
  updateCol();
  return ID;
}
{illidentifier} {
  updateCol();
  yyerror = "Illegal token";
  return ERROR;
}

/* Constants */
{integerlead0} {
  updateCol();
  yyerror = "Illegal token";
  return ERROR;
}
{integer} {
  updateCol();
  return INTCONST;
}
{character}     //TODO
{string}        {updateCol(); return processString();}
{untermstring}  {updateCol(); yyerror = "Unterminated string"; return ERROR;}

 /* Comments */
{comment}       //TODO
{untermcomment} //TODO
{multlncomment} //TODO

 /* Other */
{newline}       //TODO
{whitespace}    //TODO
. {
    updateCol();
    return ILLEGAL_TOK;
}

%%

/* user routines */

/* TODO:
Implement this function to keep track of column numbers
*/
void updateCol(){
}

/* TODO:
Implement this function to keep track of line numbers
*/
void countLines(){
}


/* TODO:
Implement this function to
check for illegal escape sequences in string literals
and
convert valid escape sequences into escaped characters
(string[0] == '\\' and string[1] == 'n', then string[0] should be '\n')
*/
int processString(){
}
